name: my_avatar
description: "A flutter project, My Avatar for Image generation."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.8
  google_sign_in: ^5.4.0
  firebase_core: ^2.17.0
  firebase_auth: ^4.20.0
  google_fonts: 6.2.1
  shared_preferences: ^2.0.13
  image_picker: ^0.8.7+3
  permission_handler: ^10.2.0
  camera: ^0.10.0+4
  logger: ^1.1.0
  firebase_storage: ^11.7.7
  uuid: 4.5.0
  json_annotation: ^4.9.0
  http: 1.2.2
  cached_network_image: ^3.4.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.2.0
  json_serializable: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
